- name: System Update
  hosts: all:!bastion
  become: true
  serial: 10
  tasks:
    - name: Update and Upgrade
      apt:
        update_cache: yes
        upgrade: full
        autoremove: yes
    - name: Check if reboot is needed
      stat:
        path: /var/run/reboot-required
      register: stat_result

    - name: Reboot
      when: stat_result.stat.exists
      reboot:

- name: Set Hostname
  hosts: all:!bastion
  become: true
  serial: 10
  tasks:
    - name: Set Hostname
      hostname:
        name: "{{ inventory_hostname }}"
      when: "inventory_hostname != ansible_hostname"

    - name: Check if reboot is needed
      stat:
        path: /var/run/reboot-required
      register: stat_result
        
    - name: Reboot
      when: stat_result.stat.exists
      reboot:

- name: Update Hosts
  hosts: all
  become: true
  tasks:
    - name: Copy Hosts File
      template: 
        src: config/hosts/hosts
        dest: /etc/hosts
