- name: Expand LVM
  hosts: all
  become: true
  tasks:
    - name: Expand LVM
      command: /home/student/extend-lvm/extend-lvm.sh  /dev/vda
      changed_when: false
- name: Make consul config folder
  hosts: [bastion]
  become: true
  tasks:
    - file: 
        path: /opt/ad
        state: directory
        owner: root
        group: root
        mode: "500"

- name: Configure Networking
  hosts: all
  become: true
  serial: 10
  tags:
    - networked
  roles:
    - role: networked
      vars:
        get_from_openstack: False

- name: Update
  hosts: all:!bastion
  become: true
  serial: 10
  tags:
    - debian
  roles:
    - debian

- name : Consul Install
  hosts: [consul, bastion]
  become: true
  tags:
    - consul
  roles:
    - role: hashicorp-software
      vars:
        programs: 
         - consul

- name : Nomad Install
  hosts: [nomad, bastion]
  become: true
  tags:
  - nomad
  roles:
    - role: hashicorp-software
      vars:
        programs: 
         - nomad

- name : Vault Install
  hosts: [vault]
  become: true
  tags:
    - vault
  roles:
    - role: hashicorp-software
      vars:
        programs: 
         - vault

- name : Hashicorp Bastion install
  hosts: [bastion]
  become: true
  roles:
    - role: hashicorp-software
      vars:
        programs: 
         - waypoint
        
- name : Consul Servers
  hosts: [consul_servers]
  become: true
  tags:
    - consul
    - consul_config
  roles:
    - role: consul-host
      vars:
        consul_server: True

- name : Consul Clients
  hosts: [consul_clients]
  become: true
  tags:
    - consul
    - consul_config
  roles:
    - role: consul-host
    
- name : Consul ACL Bootstrap
  hosts: [consul]
  become: true
  tags:
    - consul
    - consul_config
  roles:
    - role: consul-bootstrapper

- name : Nomad Servers
  hosts: [nomad_servers]
  become: true
  tags:
    - nomad
    - nomad_config
  roles:
    - role: nomad-host
      vars:
        nomad_server: True

- name : Nomad Clients
  hosts: [nomad_clients]
  tags:
  - nomad
  - nomad_config
  become: true
  roles:
    - role: nomad-host
      vars:
        nomad_client: True

- name : Vault
  hosts: [vault_clients]
  tags:
  - vault-config
  become: true
  roles:
    - role: vault-host
      vars:
        transit: 1


- name : Vault
  hosts: [vault2_clients]
  tags:
  - vault-config
  become: true
  roles:
    - role: vault-host



- name : Ceph Install
  hosts: [ceph_hosts, bastion]
  become: true
  roles:
    - ceph-host


- name : Ceph Deploy Install
  hosts: bastion
  become: true
  tasks:
    - name: Install Software
      apt: 
        update_cache: yes 
        name: "ceph-deploy"

- name : docker-install
  hosts: nomad_clients
  become: true
  tags:
    - nomad
  roles:
    - role: docker-host
      vars:
        - username: student
      
- name: LVM loopback Setup
  hosts: [ceph_osds_loopback]
  become: true
  tags:
    - lvm
  roles:
    - lvm-loopback-setup

- name: Ceph-Deploy Setup
  hosts: [ceph_monitors, ceph_managers]
  roles:
    - ceph-monitor
    - ceph-mgr

    

- name: Ceph OSD loopback
  hosts: [ceph_osds_loopback]
  roles:
    - role: ceph-osd
      vars:
        - disk_location: "{{ ceph_osd_loopback_drive }}"

- name: Format Network Volume
  hosts: backup
  become: true
  tasks:
    - name: Remove from VG
      shell: sudo vgremove `sudo vgs | grep "ceph.*128" | awk '{ print $1 }'` -ff || true
    - name: Format as ext4
      shell: sudo mkfs.ext4 /dev/vdb -F

- name: Ceph OSD Physical
  hosts: [ceph_osds_physical]
  roles:
    - role: ceph-osd
      vars:
        - disk_location: "{{ ceph_osd_physical_drive }}"
      
- name : Nomad Start
  hosts: [nomad_servers, nomad_clients]
  become: true
  tags:
    - nomad
  tasks:
    - name: Start and Enable nomad
      ansible.builtin.systemd:
        name: nomad
        enabled: true
        state: restarted