- name: Expand LVM
  hosts: all
  become: true
  tasks:
    - name: Expand LVM
      command: /home/student/extend-lvm/extend-lvm.sh  /dev/vda
      changed_when: false

- name: Configure Networking
  hosts: all
  become: true
  serial: 10
  roles:
    - role: networked
      tags:
        - networking
      vars:
        get_from_openstack: False

- name: Update
  hosts: all:!bastion
  become: true
  serial: 10
  roles:
    - debian

- name : Consul Install
  hosts: [consul, bastion]
  become: true
  roles:
    - role: hashicorp-software
      vars:
        programs: 
         - consul

- name : Nomad Install
  hosts: [nomad, bastion]
  become: true
  roles:
    - role: hashicorp-software
      vars:
        programs: 
         - nomad

- name : Hashicorp Bastion install
  hosts: [bastion]
  become: true
  roles:
    - role: hashicorp-software
      vars:
        programs: 
         - waypoint
        

- name : Ceph Install
  hosts: [ceph_hosts, bastion]
  become: true
  roles:
    - ceph-host


- name : Ceph Deploy Install
  hosts: bastion
  become: true
  tasks:
    - name: Install Software
      apt: 
        update_cache: yes 
        name: "ceph-deploy"

- name : docker-install
  hosts: nomad_clients
  become: true
  roles:
    - role: docker-host
      vars:
        - username: student
      
- name: LVM loopback Setup
  hosts: [ceph_osds_loopback]
  become: true
  roles:
    - lvm-loopback-setup

- name: Ceph-Deploy Setup
  hosts: bastion
  roles:
    - ceph-monitor
    - ceph-mgr

    

- name: Ceph OSD loopback
  hosts: [ceph_osds_loopback]
  roles:
    - role: ceph-osd
      vars:
        - disk_location: "{{ ceph_osd_loopback_drive }}"

- name: Format Network Volume
  hosts: backup
  become: true
  tasks:
    - name: Remove from VG
      shell: sudo vgremove `sudo vgs | grep "ceph.*128" | awk '{ print $1 }'` -ff || true
    - name: Format as ext4
      shell: sudo mkfs.ext4 /dev/vdb -F

- name: Ceph OSD Physical
  hosts: [ceph_osds_physical]
  roles:
    - role: ceph-osd
      vars:
        - disk_location: "{{ ceph_osd_physical_drive }}"
      
