- name: Create a directory if it does not exist
  run_once: true
  delegate_to: bastion
  ansible.builtin.file:
    path: "{{ ceph_deploy_dir }}"
    state: directory

- name: Create New Monitors
  run_once: true
  delegate_to: bastion
  command: 
    cmd: "ceph-deploy --overwrite-conf new {{ groups['ceph_monitors'] | join(' ') }}"
    chdir: "{{ ceph_deploy_dir }}"

- name: Copy Conf Tail File
  run_once: true
  delegate_to: bastion
  ansible.builtin.copy:
    src: ../config/ceph/ceph-tail.conf
    dest: "{{ ceph_deploy_dir }}/ceph-tail.conf"

- name: Edit Conf File
  run_once: true
  delegate_to: bastion
  shell:
    cmd: "cat ceph.conf ceph-tail.conf > ceph-combined.conf; mv ceph-combined.conf ceph.conf"
    chdir : "{{ ceph_deploy_dir }}"

- name: Install Ceph
  run_once: true
  delegate_to: bastion
  command: 
    cmd: "ceph-deploy --overwrite-conf install {{ groups['ceph_hosts'] | join(' ') }}"
    chdir: "{{ ceph_deploy_dir }}"

- name: Create Monitors
  run_once: true
  delegate_to: bastion
  command: 
    cmd: "ceph-deploy --overwrite-conf mon create-initial"
    chdir: "{{ ceph_deploy_dir }}"

- name: Copy Keys
  run_once: true
  delegate_to: bastion
  command: 
    cmd: "ceph-deploy --overwrite-conf admin bastion {{ groups['ceph_hosts'] | join(' ') }}"
    chdir: "{{ ceph_deploy_dir }}"