- name: Generate Host Lists
  run_once: true
  when: get_from_openstack is defined and get_from_openstack
  local_action: 
     module: command
     cmd: "{{ playbook_dir }}/../scripts/create-host-list/create.py" 
     
- name: Set Hostname
  hostname:
    name: "{{ inventory_hostname }}"
  when: "inventory_hostname != ansible_hostname"

- name: Copy Hosts File
  template: 
    src: ../config/hosts/hosts
    dest: /etc/hosts

- name: Copy Preseed
  template: 
    src: ../config/iptables-persistent/preseed
    dest: /tmp/preseed
    mode: "644"
- name: Apply Preseed
  shell: debconf-set-selections < /tmp/preseed

- name: Install IPtables-persistent
  apt: 
    update_cache: yes 
    name: "iptables-persistent"
    state: present


- name: Restart Systemd Resolve
  ansible.builtin.systemd:
    state: restarted
    name: systemd-resolved

- name: Copy NTP File
  template: 
    src: ../config/ntp/timesyncd.conf
    dest: /etc/systemd/timesyncd.conf

- name: Enable NTP
  command: timedatectl set-ntp on

- name: Restart Timesyncd
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: yes
    name: systemd-timesyncd
- name: disable unattended upgrades
  apt: 
    state: absent
    purge: yes 
    name: "unattended-upgrades"
    
- name: Check if reboot is needed
  stat:
    path: /var/run/reboot-required
  register: stat_result        
- name: Reboot
  when: stat_result.stat.exists and (never_reboot is not defined or never_reboot == True)
  reboot:
