
- name: Copy Script
  become: true
  ansible.builtin.copy:
    src: ../config/consul/check.sh
    dest: "/opt/ceph-dash-check.sh"
    mode: "555"
    owner: root
    group: root

- name: Copy Consul Service
  become: true
  template:
    src: ../config/consul/service.json
    dest: "/tmp/consul-ceph-service.json"
    mode: "644"
    owner: root
    group: root

- name: Get Secret
  slurp: 
    src: /opt/ad/consul/consul-bootstrap
  register: secret_id_b64
  changed_when: false
  become: true
  delegate_to: bastion
  run_once: True

- name: Register Service
  register: service_res
  command: "curl -i -X PUT --data @/tmp/consul-ceph-service.json -H 'X-Consul-Token: {{ secret_id_b64.content | b64decode | trim }}' http://127.0.0.1:8500/v1/agent/service/register"