- name: Add Ceph GPG apt Key
  apt_key:
    url: https://download.ceph.com/keys/release.asc
    state: present

    
- name: Add Ceph Repository
  apt_repository:
    repo: deb https://download.ceph.com/debian-pacific focal main
    state: present

- name: Install Software
  apt: 
    update_cache: yes 
    name: "{{ programs }}"