- name: Create a directory if it does not exist
  run_once: true
  delegate_to: bastion
  ansible.builtin.file:
    path: "{{ ceph_deploy_dir }}"
    state: directory

- name: Zap Disks
  delegate_to: bastion
  command: 
    cmd: "ceph-deploy disk zap {{ inventory_hostname }} {{ disk_location }}"
    chdir: "{{ ceph_deploy_dir }}"

- name: Create Disks
  delegate_to: bastion
  command: 
    cmd: "ceph-deploy osd create {{ inventory_hostname }} --data {{ disk_location }}"
    chdir: "{{ ceph_deploy_dir }}"