- name: Setup Managers
  run_once: true
  delegate_to: bastion
  command: 
    cmd: "ceph-deploy --overwrite-conf mgr create {{ groups['ceph_managers'] | join(' ') }}"
    chdir: "{{ ceph_deploy_dir }}"